<?php
    $title = "Reports"; 
    include_once 'header.php';

    $research_degrees = array('Graduates', 'Faculty', 'College', 'Senior High School');
    foreach ($research_degrees as $research_degree) {

        $total_research = mysqli_query($conn,
        "SELECT published_research.*,research_documents.*,users.role
        FROM published_research,research_documents,users
        WHERE users.role='$research_degree' AND research_documents.status='Published' AND published_research.document=research_documents.id AND research_documents.submitted_by=users.id");
        $research_rows = mysqli_num_rows($total_research);
        
        if($research_degree == "Graduates"){
            $graduates = $research_rows;
        }
        if($research_degree == "Faculty"){
            $faculty = $research_rows;
        }
        if($research_degree == "College"){
            $college = $research_rows;
        }
        if($research_degree == "Senior High School"){
            $shs = $research_rows;
        }
    }
    $research_statuses = array('Pending', 'Approved', 'Revision');
    foreach ($research_statuses as $research_status) {

        $status_research = mysqli_query($conn,
        "SELECT * FROM research_documents WHERE status='$research_status' AND instatus='active'");
        $status_rows = mysqli_num_rows($status_research);

        if($research_status == "Approved"){
            $approved = $status_rows;
        }
        if($research_status == "Revision"){
            $revision = $status_rows;
        }
        if($research_status == "Pending"){
            $pending = $status_rows;
        }
    }

    $total_users = array('Graduates', 'Faculty', 'College', 'Senior High School', 'Adviser', 'Administrator');
    $researcher = 0;
    foreach ($total_users as $user) {

        $users_role = mysqli_query($conn,
        "SELECT * FROM users WHERE role='$user' AND status<>'deactivated'");
        $users_rows = mysqli_num_rows($users_role);

        if($user == "Administrator"){
            $admin = $users_rows;
        }
        elseif($user == "Adviser"){
            $adviser = $users_rows;
        }
        else{
            $researcher = $researcher + $users_rows;
        }
    }

    $file_total = mysqli_query($conn,
    "SELECT * FROM research_documents WHERE status<>'Published'");
    $file_uploaded = mysqli_num_rows($file_total);

    $file_inactive = mysqli_query($conn,
    "SELECT * FROM research_documents WHERE instatus='inactive' AND status<>'Published'");
    $file_inactive_row = mysqli_num_rows($file_inactive);

    $publish = mysqli_query($conn,
    "SELECT * FROM published_research");
    $publish_total = mysqli_num_rows($publish);

    $users = mysqli_query($conn,
    "SELECT * FROM users WHERE status<>'deactivated'");
    $users_total = mysqli_num_rows($users);
?>
    <!-- End Navbar -->
    <div class="container-fluid py-4" id="collapsy">
        <div class="row">
            <div class="col-lg grid-margin stretch-card">
                <div class="card">
                    <div class="card-body print-container"> 
                        <h4 class="card-title text-primary">RIKDO DOCUMENTS INVENTORY REPORT</h4>
                        <div class="row mt-4"><br>
                            
                            <div class="col-lg-6 col-sm-6">
                                <h5>Overview Summary</h5>
                            </div>

                            <div class="col-lg-6 col-sm-6">
                                <small style="float: right;">Generated by: <?php if(!empty($_SESSION['account_admin'])){ echo $_SESSION['account_admin'];} ?>
                                <br>Date & Time: <?php 
                                date_default_timezone_set('Asia/Singapore');
                                echo date('F j, Y, g:i A');?>
                                </small>
                            </div>
                        </div><br>


                        <div class="row mt-2 print-container">
                            <div class="col-lg-12 col-sm-12">
                                <a href="print.php?id=<?php if(!empty($_SESSION['account_admin'])){ echo $_SESSION['account_admin'];} ?>" target="_blank" class="btn btn-light btn-sm hide_button" style="float: right;"><i class="fa fa-print hide_button"></i> Print</a>
                                <a href="generate.php?id=<?php if(!empty($_SESSION['account_admin'])){ echo $_SESSION['account_admin'];} ?>" class="btn btn-dark btn-sm hide_button" style="margin-right: 5px; float: right;"><i class="fa fa-file-pdf hide_button"></i> Generate PDF</a>
                                <table class="mt-3 print-container" id="table">
                                    <thead class="thead">
                                        <tr>
                                            <th>Category</th>
                                            <th>Total Result</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="text-align: left;">SHS Completed Research</td>
                                            <td><?php if(!empty($shs)) echo $shs; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">College Completed Research</td>
                                            <td><?php if(!empty($college)) echo $college; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Graduates Completed Research</td>
                                            <td><?php if(!empty($graduates)) echo $graduates; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Faculty Completed Research</td>
                                            <td><?php if(!empty($faculty)) echo $faculty; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;"><b>Total Completed Research</b></td>
                                            <td><b><?php if(!empty($publish_total)) echo $publish_total; else{ echo "0";}?></b></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Pending Researches</td>
                                            <td><?php if(!empty($pending)) echo $pending; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Approved Researches</td>
                                            <td><?php if(!empty($approved)) echo $approved; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Revisions Researches</td>
                                            <td><?php if(!empty($revision)) echo $revision; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Inactive Researches</td>
                                            <td><?php if(!empty($file_inactive_row)) echo $file_inactive_row; else{ echo "0";}?></td>
                                        </tr>

                                        <tr>
                                            <td style="text-align: left;"><b>Total Research Uploaded</b></td>
                                            <td><b><?php if(!empty($file_uploaded)) echo $file_uploaded; else{ echo "0";}?></b></td>
                                        </tr>

                                        <tr>
                                            <td style="text-align: left;">Number of Researchers</td>
                                            <td><?php if(!empty($researcher)) echo $researcher; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Number of Advisers</td>
                                            <td><?php if(!empty($adviser)) echo $adviser; else{ echo "0";}?></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: left;">Number of Admins</td>
                                            <td><?php if(!empty($admin)) echo $admin; else{ echo "0";}?></td>
                                        </tr>

                                        <tr>
                                            <td style="text-align: left;"><b>Total Users</b></td>
                                            <td><b><?php if(!empty($users_total)) echo $users_total; else{ echo "0";}?></b></td>
                                        </tr>
                                    </tbody>                            
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  	</div>
    
  </main>
  </div>
  <!--   Core JS Files   -->
  <script src="../assets/js/core/popper.min.js"></script>
  <script src="../assets/js/core/bootstrap.min.js"></script>
  <script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
  <script src="../assets/js/plugins/chartjs.min.js"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
    function printContent() {
        var printWindow = window.open('print.php');
        printWindow.print();
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="../assets/js/argon-dashboard.min.js?v=2.0.4"></script>
</body>
</html>