<?php
    session_start();
    require_once "db.php";

    if(isset($_GET['id'])){
        $id = $_GET['id'];
    }

    $research_degrees = array('Graduates', 'Faculty', 'College', 'Senior High School');
    foreach ($research_degrees as $research_degree) {

        $total_research = mysqli_query($conn,
        "SELECT published_research.*,research_documents.*,users.role
        FROM published_research,research_documents,users
        WHERE users.role='$research_degree' AND research_documents.status='Published' AND published_research.document=research_documents.id AND research_documents.submitted_by=users.id");
        $research_rows = mysqli_num_rows($total_research);
        
        if($research_degree == "Graduates"){
            $graduates = $research_rows;
        }
        if($research_degree == "Faculty"){
            $faculty = $research_rows;
        }
        if($research_degree == "College"){
            $college = $research_rows;
        }
        if($research_degree == "Senior High School"){
            $shs = $research_rows;
        }
    }
    $research_statuses = array('Pending', 'Approved', 'Revision');
    foreach ($research_statuses as $research_status) {

        $status_research = mysqli_query($conn,
        "SELECT * FROM research_documents WHERE status='$research_status' AND instatus='active'");
        $status_rows = mysqli_num_rows($status_research);

        if($research_status == "Approved"){
            $approved = $status_rows;
        }
        if($research_status == "Revision"){
            $revision = $status_rows;
        }
        if($research_status == "Pending"){
            $pending = $status_rows;
        }
    }

    $total_users = array('Graduates', 'Faculty', 'College', 'Senior High School', 'Adviser', 'Administrator');
    $researcher = 0;
    foreach ($total_users as $user) {

        $users_role = mysqli_query($conn,
        "SELECT * FROM users WHERE role='$user' AND status<>'deactivated'");
        $users_rows = mysqli_num_rows($users_role);

        if($user == "Administrator"){
            $admin = $users_rows;
        }
        elseif($user == "Adviser"){
            $adviser = $users_rows;
        }
        else{
            $researcher = $researcher + $users_rows;
        }
    }

    $file_total = mysqli_query($conn,
    "SELECT * FROM research_documents WHERE status<>'Published'");
    $file_uploaded = mysqli_num_rows($file_total);

    $file_inactive = mysqli_query($conn,
    "SELECT * FROM research_documents WHERE instatus='inactive' AND status<>'Published'");
    $file_inactive_row = mysqli_num_rows($file_inactive);

    $publish = mysqli_query($conn,
    "SELECT * FROM published_research");
    $publish_total = mysqli_num_rows($publish);

    $users = mysqli_query($conn,
    "SELECT * FROM users WHERE status<>'deactivated'");
    $users_total = mysqli_num_rows($users);
?>
    <!-- End Navbar -->

    <h2>RIKDO DOCUMENTS INVENTORY REPORT</h2>
    <h3>Overview Summary</h3>
                    
    <small style="float: right;">Generated by: <?php echo $id; ?>
    <br>Date & Time: <?php 
    date_default_timezone_set('Asia/Singapore');
    echo date('F j, Y, g:i A');?>
    </small><hr><br>
                    
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th>Total Result</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="2" style="text-align: left;"><b><br>Result of completed research per category</b></td>
            </tr>
            <tr>
                <td><br>SHS Research</td>
                <td><br><?php if(!empty($shs)) echo $shs; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>College Research</td>
                <td><?php if(!empty($college)) echo $college; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Graduates Research</td>
                <td><?php if(!empty($graduates)) echo $graduates; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Faculty Research</td>
                <td><?php if(!empty($faculty)) echo $faculty; else{ echo "0";}?></td>
            </tr>

            <tr>
                <td colspan="2" style="text-align: left;"><b><br>Result of submitted research document</b></td>
            </tr>
            <tr>
                <td><br>Pending</td>
                <td><br><?php if(!empty($pending)) echo $pending; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Approved</td>
                <td><?php if(!empty($approved)) echo $approved; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Revisions</td>
                <td><?php if(!empty($revision)) echo $revision; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Inactive</td>
                <td><?php if(!empty($file_inactive_row)) echo $file_inactive_row; else{ echo "0";}?></td>
            </tr>

            <tr>
                <td colspan="2" style="text-align: left;"><b><br>Result of total users per role</b></td>
            </tr>
            <tr>
                <td><br>Researchers</td>
                <td><br><?php if(!empty($researcher)) echo $researcher; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Advisers</td>
                <td><?php if(!empty($adviser)) echo $adviser; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Admins</td>
                <td><?php if(!empty($admin)) echo $admin; else{ echo "0";}?></td>
            </tr>

            <tr>
                <td colspan="2" style="text-align: left;"><b><br>Totals per category</b></td>
            </tr>
            <tr>
                <td><br>Completed Research</td>
                <td><br><?php if(!empty($publish_total)) echo $publish_total; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Research Uploaded</td>
                <td><?php if(!empty($file_uploaded)) echo $file_uploaded; else{ echo "0";}?></td>
            </tr>
            <tr>
                <td>Users</td>
                <td><?php if(!empty($users_total)) echo $users_total; else{ echo "0";}?></td>
            </tr>
        </tbody>                            
    </table>
    <hr>
</body>
</html>